name: melpazoid
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python 3.6
    #   uses: actions/setup-python@v1
    #   with: { python-version: 3.6 }
    # - name: Install
    #   run: |
    #     python -m pip install --upgrade pip
    #     sudo apt-get install emacs && emacs --version
    #     git clone https://github.com/riscy/melpazoid.git --branch develop ~/melpazoid
    #     pip install ~/melpazoid
    - name: Run
      run: |
        RECIPES=$(\
          curl --silent https://api.github.com/repos/riscy/melpa/pulls/${{ github.event.pull_request.number }}/files \
          | python -c 'import json, sys; print("\n".join([item["filename"] for item in json.load(sys.stdin) if item["filename"].startswith("recipes/")]))'\
        )
        for recipe in ${RECIPES}; do echo ${recipe}; done
